### ISSUE TITLE
Wrong accepted action

### ISSUE THREAD

**Issue by yjlcoder** [openalto/alto-domain-agent#16]
With request `{'action': 'new', 'query-type': 'path-query', 'query-desc': [], 'query-id': 1}`, the agent throw an exception. Here is the dump.

```
[qtp1692036285-22] ERROR org.snlab.unicorn.handlers.OrchestratorQueryHandler - Invalid query body:
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'action': was expecting ('true', 'false' or 'null')
 at [Source: action=new&query-type=resource-query&query-id=2; line: 1, column: 7]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
        at org.snlab.unicorn.handlers.OrchestratorQueryHandler.parseBody(OrchestratorQueryHandler.java:68)
        at org.snlab.unicorn.handlers.OrchestratorQueryHandler.handle(OrchestratorQueryHandler.java:76)
        at org.snlab.unicorn.UnicornService$ControlServiceResource.getControlStreamQuery(UnicornService.java:117)

```

**Comment by yjlcoder** [comment]
It is a mistake made by the orchestrator. Closed.
