### ISSUE TITLE
alto-nova cannot work well with java external call

### ISSUE THREAD

**Issue by fno2010** [openalto/alto-domain-agent#25]
Error log as following:

```
[Thread-21] ERROR org.snlab.unicorn.handlers.OrchestratorQueryHandler - Traceback (most recent call last):  File "/usr/bin/nova", line 4, in <module>    __import__('pkg_resources').run_script('alto-nova==0.1', 'nova')  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 748, in run_script    self.require(requires)[0].run_script(script_name, ns)  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1517, in run_script    exec(code, namespace, namespace)  File "/usr/lib/python3.4/site-packages/alto_nova-0.1-py3.4.egg/EGG-INFO/scripts/nova", line 12, in <module>    response_body = json.loads(sys.argv[1])  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads    return _default_decoder.decode(s)  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode    raise ValueError(errmsg("Expecting value", s, err.value)) from NoneValueError: Expecting value: line 1 column 1 (char 0)
```

Maybe the python version issue.

**Comment by fno2010** [comment]
Java `Runtime.exec` will transform `'` char, which is not expected.

```
command: nova '{"anes": [{"availbw": 3}, {"availbw": 7}, {"availbw": 3}], "ane-matrix": [[{"flow-id": "0"}, {"flow-id": "1"}], [{"flow-id": "1"}, {"flow-id": "2"}], [{"flow-id":"2"}]]}'

argv: ['/usr/local/bin/nova', '\'{"anes":', '[{"availbw":', '3},', '{"availbw":', '7},', '{"availbw":', '3}],', '"ane-matrix":', '[[{"flow-id":', '"0"},', '{"flow-id":', '"1"}],', '[{"flow-id":', '"1"},', '{"flow-id":', '"2"}],', '[{"flow-id":', '"2"}]]}\'']
```

**Comment by fno2010** [comment]
Split arguments into an array should fix it. [See this](https://stackoverflow.com/questions/24179964/runtime-exec-with-spaces-in-the-parameters).
